### ISSUE TITLE
这个issues相当于聊天室

### ISSUE THREAD

**Issue by Kimetiii** [yUan44/--vue#1]

**Comment by Kimetiii** [comment]
![截图](https://user-images.githubusercontent.com/42094675/54796087-c15f7580-4c89-11e9-92e6-d94615048929.PNG)
框红部分怎么嵌入到我的页面里面啊，就是点安全知识菜单下面展示红框的那部分外链内容，路由？a标签？怎么搞啊，提供点思路

**Comment by yUan44** [comment]
这肯定是路由啊

**Comment by yUan44** [comment]
自己配不就完了吗，这是子路由啊属于

**Comment by Kimetiii** [comment]
路由怎么能跳外链接，你是不是愚了，我用的路由加iframe但是问题是样式调整不好没办法只显示那个红框里面的内容
![截图](https://user-images.githubusercontent.com/42094675/54799006-3769d980-4c96-11e9-9f8c-d5cb73f52cb7.PNG)

**Comment by yUan44** [comment]
外链接直接a标签啊

**Comment by yUan44** [comment]
外链接和系统没什么关系啊，你还要在系统里显示，那只能把中间content换掉

**Comment by Kimetiii** [comment]
你他吗上面还说肯定是路由

**Comment by yUan44** [comment]
我没看你图片下面那话

**Comment by yUan44** [comment]
能不能分个行，我还以为是系统写的字呢

**Comment by Kimetiii** [comment]
http://www.sohu.com/a/206650977_679479
记录一下

**Comment by Kimetiii** [comment]
![v2-e1c4b77806c0e7a58b69bc759b213406_b](https://user-images.githubusercontent.com/42094675/54864360-1d60f180-4d91-11e9-910b-a582e89c1986.jpg)

**Comment by yUan44** [comment]
？？？
什么花里胡哨，无机六瘦的


在2019年03月23日 17:28，Kimetiii 写道：

**Comment by Kimetiii** [comment]
我现在要实现那个嵌入外部博客的 功能了，现在领导说不用部分嵌入，全页面嵌入先实现功能就行，但现在有俩问题，一个是被嵌入的博客页面位置有点尴尬，如上面给你发过的那个截图一样，在一个就是我要是点击博客里面的链接，按钮的话他就直接跳出去了，如何做到让他在我的导航里面在我们的项目里面操作博客页面，求大神（误）解答一二

**Comment by yUan44** [comment]
在2019年03月25日 10:55，Kimetiii 写道：

我现在要实现那个嵌入外部博客的 功能了，现在领导说不用部分嵌入，全页面嵌入先实现功能就行，但现在有俩问题，一个是被嵌入的博客页面位置有点尴尬，如上面给你发过的那个截图一样，在一个就是我要是点击博客里面的链接，按钮的话他就直接跳出去了，如何做到让他在我的导航里面在我们的项目里面操作博客页面，求大神（误）解答一二

**Comment by Kimetiii** [comment]
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <title>US Portal</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/dist/main.css">
    <link rel="shortcut icon" href="../us-portal-frontend/src/assents/Huawei.png" type="image/x-icon" />
</head>

<body>
    <div id="app"></div>
    <script type="text/javascript" src="/dist/vendors.js"></script>
    <script type="text/javascript" src="/dist/main.js"></script>
</body>
</html

**Comment by Kimetiii** [comment]
不行啊

**Comment by Kimetiii** [comment]
没有用

**Comment by Kimetiii** [comment]
<head>
    <title>US Portal</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/dist/main.css">
    <link rel="shortcut icon" href="../us-portal-frontend/src/assents/Huawei.png" type="image/x-icon" />
</head>

**Comment by yUan44** [comment]
有毒吧，怎么不行


在2019年03月26日 16:51，Kimetiii 写道：

不行啊

**Comment by yUan44** [comment]
写在title下面，link


在2019年03月26日 16:53，袁一祥 写道：
有毒吧，怎么不行


在2019年03月26日 16:51，Kimetiii 写道：

不行啊

**Comment by Kimetiii** [comment]
不行不行不行咋回事啊

**Comment by Kimetiii** [comment]
<link rel="shortcut icon" href="../us-portal-frontend/src/assents/Huawei.png" type="image/x-icon"/>

**Comment by yUan44** [comment]
![image](https://user-images.githubusercontent.com/32089191/54984286-7e830200-4fe9-11e9-8461-71bfb2790c9c.png)

放到static里面，然后重启项目

**Comment by yUan44** [comment]
你得把图片放到static文件夹下


在2019年03月26日 17:03，Kimetiii 写道：
<link rel="shortcut icon" href="../us-portal-frontend/src/assents/Huawei.png" type="image/x-icon"/>

**Comment by yUan44** [comment]
![image](https://user-images.githubusercontent.com/32089191/54984363-b38f5480-4fe9-11e9-9e0e-de2148113a49.png)

**Comment by Kimetiii** [comment]
你看我就是这么写的啊，href 写的相对路径而已，没必要必须是static文件夹吧

**Comment by Kimetiii** [comment]
有一个util.JS

**Comment by yUan44** [comment]
没必要你放别地方好用吗？


在2019年03月26日 17:28，Kimetiii 写道：

有一个util.JS

**Comment by yUan44** [comment]
你那几把图片什么格式，ico后缀的才行，你弄个png干哈

**Comment by yUan44** [comment]
![image](https://user-images.githubusercontent.com/32089191/55044510-9011eb80-5075-11e9-845a-344914820bd6.png)
xiaojigen小几根

**Comment by Kimetiii** [comment]
我在这个仓库开了一个新的issues
