### ISSUE TITLE
开一个新issues

### ISSUE THREAD

**Issue by Kimetiii** [yUan44/--vue#2]
你干嘛呢？出来唠唠

**Comment by yUan44** [comment]
唠什么？你没有事干了啊

**Comment by Kimetiii** [comment]
昂，没有太着急的事，暂时不太想干，一般上午都是静默时间，你昨晚干啥了

**Comment by Kimetiii** [comment]
小绿草，你想要小孩了啊

**Comment by yUan44** [comment]
？？？

**Comment by yUan44** [comment]
他妈的，昨晚和我哥上王者呢

**Comment by Kimetiii** [comment]
？？？那上去了吗

**Comment by yUan44** [comment]
昨晚练腿了，洗澡，哪有功夫玩

**Comment by yUan44** [comment]
没上去，擦

**Comment by Kimetiii** [comment]
练腿怎么练？你又去健身房了？

**Comment by yUan44** [comment]
跟着keep练啊，哥哥是VIP

**Comment by yUan44** [comment]
![image](https://user-images.githubusercontent.com/32089191/55123811-f57ddf00-513e-11e9-9d29-e294af8f1f9c.png)

**Comment by Kimetiii** [comment]
原来你没办健身房卡，一直在家里自己练？

**Comment by Kimetiii** [comment]
你这ui略丑

**Comment by yUan44** [comment]
800一年的，这么便宜不办不亏了吗

**Comment by yUan44** [comment]
饿了吗的组件

**Comment by Kimetiii** [comment]
不带游泳吧，可以洗澡，设备多吗，位置在哪

**Comment by yUan44** [comment]
金科

**Comment by Kimetiii** [comment]
elementui感觉还是有点丑

**Comment by Kimetiii** [comment]
金科在哪？你天天骑电瓶车去？你车票下来了吗

**Comment by yUan44** [comment]
说了你也不知道啊，反正不是太远，最基本的，没有游泳

**Comment by yUan44** [comment]
周末才去，一般不爱动弹

**Comment by yUan44** [comment]
钱才交，等暂住证下来才能去练车

**Comment by Kimetiii** [comment]
你周末去一次感觉不是很上算啊

**Comment by yUan44** [comment]
昨天审核才通过，ems邮寄过来，估计得等几天
然后去体检，报考科目1
过了才能练车

**Comment by Kimetiii** [comment]
你科目1看了吗？不能挂了啊

**Comment by yUan44** [comment]
现在还没考过90分

**Comment by Kimetiii** [comment]
那你估计悬了，以我多年经验来看，你这个车票不好拿了，我第一次考科目一就考了个双百

**Comment by yUan44** [comment]
你有个鸡毛经验啊？哪来的双百

**Comment by Kimetiii** [comment]
反正你这个不好弄了，困难

**Comment by Kimetiii** [comment]
想出去玩了，感觉最近有点累

**Comment by yUan44** [comment]
出去玩不是更累

**Comment by yUan44** [comment]
费钱还费力

**Comment by Kimetiii** [comment]
你什么之后能给我解决一下人生大事，赶紧花楼花楼啊

**Comment by yUan44** [comment]
他妈的，我是老鸨吗

**Comment by Kimetiii** [comment]
我跑鞋到广州机场了，今早看的

**Comment by yUan44** [comment]
那快了，明天就差不多到了

**Comment by Kimetiii** [comment]
什么开发实习生给我安排上啊

**Comment by yUan44** [comment]
学校资源都不抓紧，现在上班的妹子都吃钱，天天穿的花枝招展，得钱了

**Comment by yUan44** [comment]
开发的没有啊，不招人了

**Comment by Kimetiii** [comment]
学校怎么抓紧啊主要，妈的去耍流氓啊

**Comment by Kimetiii** [comment]
昨天下雨，晚上没跑步，感觉浑身难受

**Comment by Kimetiii** [comment]
我感觉我要加长度了，我已经跑了一个礼拜两公里，今天挑战一下三公里

**Comment by yUan44** [comment]
我这现在还在下
毁了，昨晚打雷，暴雨

**Comment by yUan44** [comment]
给我弄醒了，出去收衣服，一看5点了

**Comment by yUan44** [comment]
我以前都4公里

**Comment by Kimetiii** [comment]
这个天不去打会儿篮球？那也天可惜了吧，室友老胡买了个篮球，太不容易了，109斯伯丁

**Comment by Kimetiii** [comment]
我以前还12公里呢

**Comment by yUan44** [comment]
打水球啊

**Comment by yUan44** [comment]
moment.js 是个好东西

**Comment by Kimetiii** [comment]
recent你会用吗？听说是最牛逼的？刚才帮实习生看问题了

**Comment by yUan44** [comment]
recent是什么？？？
react？？？

**Comment by Kimetiii** [comment]
对，你会吗？这个怎么样，牛逼吗

**Comment by yUan44** [comment]
不会，牛逼啊，就是render

**Comment by yUan44** [comment]
全是组件化开发，render方法

**Comment by Kimetiii** [comment]
https://github.com/997icu/996.ICU/issues
这帖子火了

**Comment by yUan44** [comment]
![image](https://user-images.githubusercontent.com/32089191/55144149-23811480-517b-11e9-84d8-25a2d962d5f6.png)

**Comment by yUan44** [comment]
一会好拍片了，中国程序员选在都在划水

**Comment by Kimetiii** [comment]
这贴完全变成水贴了，我还水了一贴

**Comment by Kimetiii** [comment]
![image](https://user-images.githubusercontent.com/42094675/55144222-4dd2d200-517b-11e9-9c71-2413b9f842ab.png)

**Comment by Kimetiii** [comment]
太逗了

**Comment by Kimetiii** [comment]
![image](https://user-images.githubusercontent.com/42094675/55144284-71961800-517b-11e9-89a0-a862e65b3193.png)
![image](https://user-images.githubusercontent.com/42094675/55144299-78bd2600-517b-11e9-9e16-6e94c6c707e7.png)

**Comment by Kimetiii** [comment]
![image](https://user-images.githubusercontent.com/42094675/55144321-88d50580-517b-11e9-9b41-70c73afe1d85.png)
![image](https://user-images.githubusercontent.com/42094675/55144340-97bbb800-517b-11e9-950e-b1f7eb51c97d.png)
![image](https://user-images.githubusercontent.com/42094675/55144346-9c806c00-517b-11e9-85ee-283763c64f8f.png)

**Comment by Kimetiii** [comment]
好无聊啊，你在干什么

**Comment by yUan44** [comment]
我啊，在刷知乎啊，无聊还不下班啊

**Comment by yUan44** [comment]
在看车，妈的，各种看，就是没钱买

**Comment by Kimetiii** [comment]
链接: https://pan.baidu.com/s/1X66u_udF5ZxDhcC4AJP5lA  密码:ul2w
这个压缩文件帮我下载一下然后传到仓库里啊

**Comment by Kimetiii** [comment]
不用了
